# Generated by Django 5.2.7 on 2025-10-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_method_order_tracking_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
